# Generated by Django 4.2.5 on 2023-09-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True),
        ),
    ]
